<a href="https://colab.research.google.com/github/abhi-11nav/ConsumerComplaints-Classifaction/blob/main/ConsumerComplaints_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataset Credits:

https://www.kaggle.com/datasets/shashwatwork/consume-complaints-dataset-fo-nlp

In [1]:
# Importing libraries for dataset manipulations

import pandas as pd 
import numpy as np 

In [2]:
# Cloning the github repository

!git clone https://github.com/abhi-11nav/ConsumerComplaints-Classifaction.git

Cloning into 'ConsumerComplaints-Classifaction'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 25 (delta 7), reused 2 (delta 2), pack-reused 9
Unpacking objects: 100% (25/25), done.


In [3]:
# Importing the data and storing it in a varibale (data)

data = pd.read_csv("/content/ConsumerComplaints-Classifaction/complaints_processed.csv")

In [4]:
# Peeking at the data (first few columns)

data.head(10)

Unnamed: 0           product  \
0           0       credit_card   
1           1       credit_card   
2           2    retail_banking   
3           3  credit_reporting   
4           4  credit_reporting   
5           5  credit_reporting   
6           6  credit_reporting   
7           7  credit_reporting   
8           8  credit_reporting   
9           9  credit_reporting   

                                           narrative  
0  purchase order day shipping amount receive pro...  
1  forwarded message date tue subject please inve...  
2  forwarded message cc sent friday pdt subject f...  
3  payment history missing credit report speciali...  
4  payment history missing credit report made mis...  
5  payment history missing credit report made mis...  
6  va date complaint experian credit bureau invol...  
7  account reported abbreviated name full name se...  
8  account reported abbreviated name full name se...  
9  usdoexxxx account reported abbreviated name fu...

In [6]:
data.iloc[4].isna()

Unnamed: 0    False
product       False
narrative     False
Name: 4, dtype: bool

In [7]:
# Dropping the duplicate column (Unnamed:0)

data.drop('Unnamed: 0', axis=1, inplace=True)

In [8]:
# Verifying that the column is dropped

data.head()

product                                          narrative
0       credit_card  purchase order day shipping amount receive pro...
1       credit_card  forwarded message date tue subject please inve...
2    retail_banking  forwarded message cc sent friday pdt subject f...
3  credit_reporting  payment history missing credit report speciali...
4  credit_reporting  payment history missing credit report made mis...

In [9]:
# Shape of the data 

data.shape

(162421, 2)

In [10]:
# Number of categories to be classified 

data['product'].value_counts()

credit_reporting       91179
debt_collection        23150
mortgages_and_loans    18990
credit_card            15566
retail_banking         13536
Name: product, dtype: int64

In [11]:
# Dropping all null values


data.dropna(inplace=True)


In [12]:
missing_val_count = 0 

if data["narrative"].isna().any() == True:

  missing_val_count += 1
  
if missing_val_count>0:
  print("Yes there exists null values", missing_val_count)
else:
  print("No missing values: good to go ahead")

No missing values: good to go ahead


In [13]:
len(data)

162411

## Observation:

We can observe that there is a dominance of "credit reporting" category in product class. Let us search for duplicate and or data with similar semantic meanings in the data. 

First, let's do some text preprocessing to clean the data (converting to lower case, removal of punctuations, etc).

# TEXT PREPROCESSING 
### DO NOT EXECUTE

In [ ]:
# Storing the text in a list. 

narrative = [text for text in data['narrative']]

In [ ]:
# Importing the libraries required for text preprocessing 

import re 

import nltk 
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [ ]:
# Creating an object for WordNetLemmatizer 

lemmatizer = WordNetLemmatizer()

In [ ]:
# Library for computing runtime 
from tqdm import tqdm


# Getting rid of all punctuations and numeric values in the data. Also convert the data into lower case. 
for index in tqdm(range(0,len(narrative))):
  temp_variable = (re.sub('[^a-zA-Z]',' ',str(narrative[index])))
  narrative[index] = " ".join(word for word in str(narrative[index]).split()).lower()

100%|██████████| 162411/162411 [00:04<00:00, 34207.58it/s]


In [ ]:
# Applying lemmatization and removing the stopwords.

from tqdm import tqdm 


for index in tqdm(range(len(narrative))):
  temp_list = []
  for word in narrative[index].split():
    if word not in stopwords.words("english"):
      temp_list.append(word)
  narrative[index] = " ".join(lemmatizer.lemmatize(words) for words in temp_list) 


  # Already performed the operation once and store the data in "processex_text.csv"

  1%|          | 1005/162411 [00:20<30:38, 87.79it/s]

In [ ]:
# Saving the processed text in excel file 

pd.DataFrame(narrative).to_csv("processed_text.csv")

## Jaccard Similary on "credit_reporting" category. 

In [ ]:
arr = [[1,1,1,0,0,0],[0,1,0,0,0,0],[1,1,1,0,0,0],[0,0,2,4,4,0],[0,0,0,2,0,0],[0,0,1,2,4,0]]

In [ ]:
arr

In [ ]:
def hourglassSum(arr):
    # Write your code here
    num, sum_ = 1,0
    list_ = []
    n=0
    while(n<len(arr[0])-4):
        for i in range(len(arr[0+n:3+n])):
            for j in range(len(arr[0+n:3+n])):
                sum_ += arr[i][j];
        n+=1
        list_.append(sum_)
    return max(list_)

In [ ]:
print(hourglassSum(arr))

In [ ]:
print("There are a total of",len(narrative),"sentences")

In [ ]:
def jaccard_similarity(document1, document2):
  a = set(document1.split())
  b = set(document2.split())

  c = a.intersection(b)

  return len(c)/ (len(a)+len(b)-len(c))

In [ ]:
from tqdm import tqdm

si = narrative

for index in tqdm(range(len(narrative))):
  for each in range(len(narrative)):
    if jaccard_similarity(str(narrative[index]), str(narrative[each])) > 0.9:
      si[index] = "duplicate"

In [ ]:
jaccard_similarity(narrative[0],narrative[7324])

In [ ]:
narrative[0]

In [ ]:
from tqdm import tqdm 

#WORD2VEC MODEL

In [14]:
# Import word_tokenize and downlaoding punkt

import nltk

from nltk import word_tokenize
nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [15]:
import gensim 

from gensim.models import Word2Vec 

In [ ]:
word2vec_model = gensim.models.Word2Vec(list_of_words, window=5, min_count=2);

In [ ]:
processed_data = []

for words in tqdm(list_of_words):
  processed_data.append(np.mean([word2vec_model.wv[word] for word in words if word in word2vec_model.wv.index2word], axis=0))

# **EXECUTE**

# MODEL

In [19]:
# Reading the data from processed data

processed_data = pd.read_csv("processed_text.csv")

narrative = [str(sent) for sent in processed_data['0']]

 Credits for word embedding code - https://towardsdatascience.com/creating-word-embeddings-coding-the-word2vec-algorithm-in-python-using-deep-learning-b337d0ba17a8

In [43]:
# Defining the window for context
window = 1

# Creating a placeholder for the scanning of the word list
word_lists = []
all_text = []


for text in narrative:


    # Creating a context dictionary
    for i, word in enumerate(text.split()):
        for w in range(window):
            # Getting the context that is ahead by *window* words
            if i + 1 + w < len(text.split()): 
                word_lists.append([word] + [text.split()[(i + 1 + w)]])
            # Getting the context that is behind by *window* words    
            if i - w - 1 >= 0:
                word_lists.append([word] + [text.split()[(i - w - 1)]])

In [45]:
pd.DataFrame(word_lists).to_csv("embeddings.csv")

In [46]:
embeddings = pd.read_csv("embeddings.csv")

In [47]:
len(embeddings)

25728480

In [49]:
word_pairs = []

for i in tqdm(range(len(embeddings))):
  word_pairs.append([embeddings["0"][i],embeddings["1"][i]])

100%|██████████| 25728480/25728480 [04:49<00:00, 88830.89it/s]


In [50]:
# Downloading the required libraries

import nltk 
from nltk import word_tokenize
nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [51]:
# List to store the words in the corpus


list_of_words = []

from tqdm import tqdm

for index in tqdm(range(len(narrative))):
  for words in set(word_tokenize(narrative[index])):
    list_of_words.append(words)

100%|██████████| 162411/162411 [01:00<00:00, 2704.21it/s]


In [58]:
# Saving the list of words in 
import pandas as pd 

pd.DataFrame(set(list_of_words)).to_csv("unique_words.csv")

In [59]:
unique_words = pd.read_csv("unique_words.csv")

unique_words.head()

Unnamed: 0           0
0           0     onlyway
1           1    timesand
2           2    exposing
3           3     dispued
4           4  unexpended

In [60]:
words = [word for word in unique_words["0"]]

In [ ]:
## Code to generate/assign individual id/idnex to every word. (helpful for one hot encoding)

def word_index(all_words):
  all_words.sort()

  unique_word_dict = {}

  for index, word in enumerate(all_words):
    unique_word_dict.update({
        word: index
    })
  
  return unique_word_dict

In [ ]:
# All the indexes are stored in word_indexes varaiable. 


word_indexes = word_index(list_of_words)

In [ ]:
# Now we create a matrix that has vectorized form of the word. 

from scipy import sparse

words_length = len(word_indexes)

# Creating empty matrices

X = []
y = []

for index, words in tqdm(enumerate(word_lists)):
  main_word = word_indexes.get(words[0])
  context_word = word_indexes.get(words[1])

  X_row = np.zeros(words_length)
  y_row = np.zeros(words_length)

  X_row[main_word] = 1
  y_row[context_word] = 1

  X.append(X_row)
  y.append(y_row)

X = np.asarray(X)
y = np.asarray(y)

# ONE HOT ENCODING 

In [ ]:
vocab_size = len(list_of_words)

In [ ]:
vocab_size

8390

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
onehot_repr=[one_hot(words,vocab_size)for words in narrative] 

In [ ]:
len(narrative)

162411

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3032 5466 7492 ... 1027 2430 3806]
 [4120 8214 7491 ... 3784 4159 5113]
 [5972 3655 5589 ... 7915 1547 1439]
 ...
 [2926    0    0 ...    0    0    0]
 [2926    0    0 ...    0    0    0]
 [2926    0    0 ...    0    0    0]]


In [ ]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(vocab_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 20, 40)            335600    
                                                                 
 lstm_2 (LSTM)               (None, 100)               56400     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 392,101
Trainable params: 392,101
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(data["product"])

In [ ]:
y = data['product']

In [ ]:
y.value_counts()

credit_reporting       91172
debt_collection        23148
mortgages_and_loans    18990
credit_card            15566
retail_banking         13535
Name: product, dtype: int64

In [ ]:
for val in range(data.index):

    if y[val] == 'credit_reporting':
      y[val] = 0
    elif y[val] == 'debt_collection':
      y[val]= 1
    elif y[val] == 'credit_card':
      y[val]= 2
    elif y[val] == 'retail_banking':
      y[val]= 1
    else:
      y[val] = 3

TypeError: ignored

In [ ]:
max(data.index)

162420

In [ ]:
y[1080:1091]

1080                   0
1081                   0
1082                   3
1083                   3
1084                   0
1085                   0
1086                   0
1087                   0
1088                   0
1090    credit_reporting
1091    credit_reporting
Name: product, dtype: object

In [ ]:
X_final.shape

(162411, 20)

In [ ]:
y_final.shape

(162411,)

#

In [ ]:
# Splitting the data

from sklearn.model_selection import train_test_split 

train_X, test_X, train_y, test_y = train_test_split(X_final, y_final, test_size=0.1, random_state=143)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
model = GaussianNB()

In [ ]:
model.fit(train_X, train_y)

GaussianNB()

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
for val in range(len(test_X)):
  test_X[0] = test_X[0].reshape(1,-1)

In [ ]:
scores = []

In [ ]:
for val in test_X:
  scores.append(model.predict(test_X[0].reshape(1,-1)))

In [ ]:
accuracy_score(test_y, scores)

0.5698805565817018

# LSTM RNN MODEL

In [ ]:
model.fit(train_X,train_y,validation_data=(test_X,test_y),epochs=10,batch_size=64)

Epoch 1/10


UnimplementedError: ignored